// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz9c7iGWqZpuA5_O7GtsA3XERZG0s_iTs',
    appId: '1:844389449463:web:164c9a46b336d59b1fddf2',
    messagingSenderId: '844389449463',
    projectId: 'vcare-db0f2',
    authDomain: 'vcare-db0f2.firebaseapp.com',
    storageBucket: 'vcare-db0f2.firebasestorage.app',
    measurementId: 'G-W55FS5D7ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa6Z7hF4O74QkBDbu088vIiIWSxfrzYQ4',
    appId: '1:844389449463:android:6af5d42d3e4b968c1fddf2',
    messagingSenderId: '844389449463',
    projectId: 'vcare-db0f2',
    storageBucket: 'vcare-db0f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrDoPmDo7xtheS0CL0GFBB8AHVyZG8qOQ',
    appId: '1:844389449463:ios:47cd3bdd487880c41fddf2',
    messagingSenderId: '844389449463',
    projectId: 'vcare-db0f2',
    storageBucket: 'vcare-db0f2.firebasestorage.app',
    iosBundleId: 'com.example.vCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrDoPmDo7xtheS0CL0GFBB8AHVyZG8qOQ',
    appId: '1:844389449463:ios:47cd3bdd487880c41fddf2',
    messagingSenderId: '844389449463',
    projectId: 'vcare-db0f2',
    storageBucket: 'vcare-db0f2.firebasestorage.app',
    iosBundleId: 'com.example.vCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz9c7iGWqZpuA5_O7GtsA3XERZG0s_iTs',
    appId: '1:844389449463:web:c7bb1514d020ac6d1fddf2',
    messagingSenderId: '844389449463',
    projectId: 'vcare-db0f2',
    authDomain: 'vcare-db0f2.firebaseapp.com',
    storageBucket: 'vcare-db0f2.firebasestorage.app',
    measurementId: 'G-TE0KMMB5C2',
  );
}
